export default {
    ADD_TODO: 'ADD_TODO',
    ADD_TODOS: 'ADD_TODOS',
    SET_SEARCH_TEXT: 'SET_SEARCH_TEXT',
    TOGGLE_SEARCH_ALL: 'TOGGLE_SEARCH_ALL',
    TOGGLE_TODO: 'TOGGLE_TODO',
    TODO_NOT_FOUND: 'TODO_NOT_FOUND',
    UPDATE_TODO: 'UPDATE_TODO',
    START_LOADING: 'START_LOADING',
    STOP_LOADING: 'STOP_LOADING',
};